apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-planet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-planet
  template:
    metadata:
      labels:
        app: ai-planet
    spec:
      containers:
      - name: ai-planet-container
        image: amazingatul/ai-planet:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        resources: 
          limits:
            cpu: "1" 
            memory: "512Mi" 
          requests:
            cpu: "0.5" 
            memory: "256Mi" 

