apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ai-planet-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-planet
  template:
    metadata:
      labels:
        app: ai-planet
    spec:
      containers:
      - name: ai-planet-container
        image: amazingatul/ai-planet:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
  strategy:
    canary:
      steps:
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
      - pause:
          duration: 10s
